[build]
  base = "/"
  publish = "dist"
  command = "npm run build:dev"

[context.production]
  command = "npm run build"

[dev]
  framework = "#custom"
  command = "npm run serve"
  targetPort = 5000
  port = 8080
  publish = "dist"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

